repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
      exclude: cpp\/proto\/|java\/proto\/
  -   id: trailing-whitespace
      exclude: cpp\/proto\/|java\/proto\/
- repo: local
  hooks:
    - id: custom-script-file
      name: custom-script-file
      entry: scripts/lint.sh
      language: script
      types: [proto]
      pass_filenames: false
