// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/geo/v1/geometry.proto

package geo.v1;

/**
 * Protobuf type {@code geo.v1.FileRequestChunk}
 */
public final class FileRequestChunk extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geo.v1.FileRequestChunk)
    FileRequestChunkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileRequestChunk.newBuilder() to construct.
  private FileRequestChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileRequestChunk() {
    resultEncodingType_ = 0;
    data_ = com.google.protobuf.ByteString.EMPTY;
    fileName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileRequestChunk();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileRequestChunk(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            geo.v1.GeometryRequest.Builder subBuilder = null;
            if (nestedRequest_ != null) {
              subBuilder = nestedRequest_.toBuilder();
            }
            nestedRequest_ = input.readMessage(geo.v1.GeometryRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nestedRequest_);
              nestedRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            resultEncodingType_ = rawValue;
            break;
          }
          case 26: {
            geo.v1.ProjectionData.Builder subBuilder = null;
            if (inputProj_ != null) {
              subBuilder = inputProj_.toBuilder();
            }
            inputProj_ = input.readMessage(geo.v1.ProjectionData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(inputProj_);
              inputProj_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            geo.v1.ProjectionData.Builder subBuilder = null;
            if (resultProj_ != null) {
              subBuilder = resultProj_.toBuilder();
            }
            resultProj_ = input.readMessage(geo.v1.ProjectionData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resultProj_);
              resultProj_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {

            data_ = input.readBytes();
            break;
          }
          case 56: {

            size_ = input.readInt64();
            break;
          }
          case 64: {

            offset_ = input.readInt64();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          case 80: {

            isLastChunk_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return geo.v1.GeometryProto.internal_static_geo_v1_FileRequestChunk_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return geo.v1.GeometryProto.internal_static_geo_v1_FileRequestChunk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            geo.v1.FileRequestChunk.class, geo.v1.FileRequestChunk.Builder.class);
  }

  /**
   * Protobuf enum {@code geo.v1.FileRequestChunk.FileType}
   */
  public enum FileType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SHAPEFILE = 0;</code>
     */
    SHAPEFILE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SHAPEFILE = 0;</code>
     */
    public static final int SHAPEFILE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FileType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FileType forNumber(int value) {
      switch (value) {
        case 0: return SHAPEFILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FileType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FileType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
            public FileType findValueByNumber(int number) {
              return FileType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return geo.v1.FileRequestChunk.getDescriptor().getEnumTypes().get(0);
    }

    private static final FileType[] VALUES = values();

    public static FileType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FileType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:geo.v1.FileRequestChunk.FileType)
  }

  public static final int NESTED_REQUEST_FIELD_NUMBER = 1;
  private geo.v1.GeometryRequest nestedRequest_;
  /**
   * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
   * @return Whether the nestedRequest field is set.
   */
  @java.lang.Override
  public boolean hasNestedRequest() {
    return nestedRequest_ != null;
  }
  /**
   * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
   * @return The nestedRequest.
   */
  @java.lang.Override
  public geo.v1.GeometryRequest getNestedRequest() {
    return nestedRequest_ == null ? geo.v1.GeometryRequest.getDefaultInstance() : nestedRequest_;
  }
  /**
   * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
   */
  @java.lang.Override
  public geo.v1.GeometryRequestOrBuilder getNestedRequestOrBuilder() {
    return getNestedRequest();
  }

  public static final int RESULT_ENCODING_TYPE_FIELD_NUMBER = 2;
  private int resultEncodingType_;
  /**
   * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
   * @return The enum numeric value on the wire for resultEncodingType.
   */
  @java.lang.Override public int getResultEncodingTypeValue() {
    return resultEncodingType_;
  }
  /**
   * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
   * @return The resultEncodingType.
   */
  @java.lang.Override public geo.v1.Encoding getResultEncodingType() {
    @SuppressWarnings("deprecation")
    geo.v1.Encoding result = geo.v1.Encoding.valueOf(resultEncodingType_);
    return result == null ? geo.v1.Encoding.UNRECOGNIZED : result;
  }

  public static final int INPUT_PROJ_FIELD_NUMBER = 3;
  private geo.v1.ProjectionData inputProj_;
  /**
   * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
   * @return Whether the inputProj field is set.
   */
  @java.lang.Override
  public boolean hasInputProj() {
    return inputProj_ != null;
  }
  /**
   * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
   * @return The inputProj.
   */
  @java.lang.Override
  public geo.v1.ProjectionData getInputProj() {
    return inputProj_ == null ? geo.v1.ProjectionData.getDefaultInstance() : inputProj_;
  }
  /**
   * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
   */
  @java.lang.Override
  public geo.v1.ProjectionDataOrBuilder getInputProjOrBuilder() {
    return getInputProj();
  }

  public static final int RESULT_PROJ_FIELD_NUMBER = 5;
  private geo.v1.ProjectionData resultProj_;
  /**
   * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
   * @return Whether the resultProj field is set.
   */
  @java.lang.Override
  public boolean hasResultProj() {
    return resultProj_ != null;
  }
  /**
   * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
   * @return The resultProj.
   */
  @java.lang.Override
  public geo.v1.ProjectionData getResultProj() {
    return resultProj_ == null ? geo.v1.ProjectionData.getDefaultInstance() : resultProj_;
  }
  /**
   * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
   */
  @java.lang.Override
  public geo.v1.ProjectionDataOrBuilder getResultProjOrBuilder() {
    return getResultProj();
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 6 [json_name = "data"];</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int SIZE_FIELD_NUMBER = 7;
  private long size_;
  /**
   * <code>int64 size = 7 [json_name = "size"];</code>
   * @return The size.
   */
  @java.lang.Override
  public long getSize() {
    return size_;
  }

  public static final int OFFSET_FIELD_NUMBER = 8;
  private long offset_;
  /**
   * <code>int64 offset = 8 [json_name = "offset"];</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int FILE_NAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object fileName_;
  /**
   * <code>string file_name = 9 [json_name = "fileName"];</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string file_name = 9 [json_name = "fileName"];</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_LAST_CHUNK_FIELD_NUMBER = 10;
  private boolean isLastChunk_;
  /**
   * <code>bool is_last_chunk = 10 [json_name = "isLastChunk"];</code>
   * @return The isLastChunk.
   */
  @java.lang.Override
  public boolean getIsLastChunk() {
    return isLastChunk_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nestedRequest_ != null) {
      output.writeMessage(1, getNestedRequest());
    }
    if (resultEncodingType_ != geo.v1.Encoding.UNKNOWN_ENCODING.getNumber()) {
      output.writeEnum(2, resultEncodingType_);
    }
    if (inputProj_ != null) {
      output.writeMessage(3, getInputProj());
    }
    if (resultProj_ != null) {
      output.writeMessage(5, getResultProj());
    }
    if (!data_.isEmpty()) {
      output.writeBytes(6, data_);
    }
    if (size_ != 0L) {
      output.writeInt64(7, size_);
    }
    if (offset_ != 0L) {
      output.writeInt64(8, offset_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, fileName_);
    }
    if (isLastChunk_ != false) {
      output.writeBool(10, isLastChunk_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nestedRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNestedRequest());
    }
    if (resultEncodingType_ != geo.v1.Encoding.UNKNOWN_ENCODING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, resultEncodingType_);
    }
    if (inputProj_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInputProj());
    }
    if (resultProj_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getResultProj());
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, data_);
    }
    if (size_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, size_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, offset_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, fileName_);
    }
    if (isLastChunk_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isLastChunk_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof geo.v1.FileRequestChunk)) {
      return super.equals(obj);
    }
    geo.v1.FileRequestChunk other = (geo.v1.FileRequestChunk) obj;

    if (hasNestedRequest() != other.hasNestedRequest()) return false;
    if (hasNestedRequest()) {
      if (!getNestedRequest()
          .equals(other.getNestedRequest())) return false;
    }
    if (resultEncodingType_ != other.resultEncodingType_) return false;
    if (hasInputProj() != other.hasInputProj()) return false;
    if (hasInputProj()) {
      if (!getInputProj()
          .equals(other.getInputProj())) return false;
    }
    if (hasResultProj() != other.hasResultProj()) return false;
    if (hasResultProj()) {
      if (!getResultProj()
          .equals(other.getResultProj())) return false;
    }
    if (!getData()
        .equals(other.getData())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (getIsLastChunk()
        != other.getIsLastChunk()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNestedRequest()) {
      hash = (37 * hash) + NESTED_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getNestedRequest().hashCode();
    }
    hash = (37 * hash) + RESULT_ENCODING_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + resultEncodingType_;
    if (hasInputProj()) {
      hash = (37 * hash) + INPUT_PROJ_FIELD_NUMBER;
      hash = (53 * hash) + getInputProj().hashCode();
    }
    if (hasResultProj()) {
      hash = (37 * hash) + RESULT_PROJ_FIELD_NUMBER;
      hash = (53 * hash) + getResultProj().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSize());
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + IS_LAST_CHUNK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLastChunk());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static geo.v1.FileRequestChunk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.FileRequestChunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.FileRequestChunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static geo.v1.FileRequestChunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static geo.v1.FileRequestChunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static geo.v1.FileRequestChunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(geo.v1.FileRequestChunk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geo.v1.FileRequestChunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geo.v1.FileRequestChunk)
      geo.v1.FileRequestChunkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return geo.v1.GeometryProto.internal_static_geo_v1_FileRequestChunk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return geo.v1.GeometryProto.internal_static_geo_v1_FileRequestChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              geo.v1.FileRequestChunk.class, geo.v1.FileRequestChunk.Builder.class);
    }

    // Construct using geo.v1.FileRequestChunk.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nestedRequestBuilder_ == null) {
        nestedRequest_ = null;
      } else {
        nestedRequest_ = null;
        nestedRequestBuilder_ = null;
      }
      resultEncodingType_ = 0;

      if (inputProjBuilder_ == null) {
        inputProj_ = null;
      } else {
        inputProj_ = null;
        inputProjBuilder_ = null;
      }
      if (resultProjBuilder_ == null) {
        resultProj_ = null;
      } else {
        resultProj_ = null;
        resultProjBuilder_ = null;
      }
      data_ = com.google.protobuf.ByteString.EMPTY;

      size_ = 0L;

      offset_ = 0L;

      fileName_ = "";

      isLastChunk_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return geo.v1.GeometryProto.internal_static_geo_v1_FileRequestChunk_descriptor;
    }

    @java.lang.Override
    public geo.v1.FileRequestChunk getDefaultInstanceForType() {
      return geo.v1.FileRequestChunk.getDefaultInstance();
    }

    @java.lang.Override
    public geo.v1.FileRequestChunk build() {
      geo.v1.FileRequestChunk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public geo.v1.FileRequestChunk buildPartial() {
      geo.v1.FileRequestChunk result = new geo.v1.FileRequestChunk(this);
      if (nestedRequestBuilder_ == null) {
        result.nestedRequest_ = nestedRequest_;
      } else {
        result.nestedRequest_ = nestedRequestBuilder_.build();
      }
      result.resultEncodingType_ = resultEncodingType_;
      if (inputProjBuilder_ == null) {
        result.inputProj_ = inputProj_;
      } else {
        result.inputProj_ = inputProjBuilder_.build();
      }
      if (resultProjBuilder_ == null) {
        result.resultProj_ = resultProj_;
      } else {
        result.resultProj_ = resultProjBuilder_.build();
      }
      result.data_ = data_;
      result.size_ = size_;
      result.offset_ = offset_;
      result.fileName_ = fileName_;
      result.isLastChunk_ = isLastChunk_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof geo.v1.FileRequestChunk) {
        return mergeFrom((geo.v1.FileRequestChunk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(geo.v1.FileRequestChunk other) {
      if (other == geo.v1.FileRequestChunk.getDefaultInstance()) return this;
      if (other.hasNestedRequest()) {
        mergeNestedRequest(other.getNestedRequest());
      }
      if (other.resultEncodingType_ != 0) {
        setResultEncodingTypeValue(other.getResultEncodingTypeValue());
      }
      if (other.hasInputProj()) {
        mergeInputProj(other.getInputProj());
      }
      if (other.hasResultProj()) {
        mergeResultProj(other.getResultProj());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.getSize() != 0L) {
        setSize(other.getSize());
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (other.getIsLastChunk() != false) {
        setIsLastChunk(other.getIsLastChunk());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      geo.v1.FileRequestChunk parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (geo.v1.FileRequestChunk) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private geo.v1.GeometryRequest nestedRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.GeometryRequest, geo.v1.GeometryRequest.Builder, geo.v1.GeometryRequestOrBuilder> nestedRequestBuilder_;
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     * @return Whether the nestedRequest field is set.
     */
    public boolean hasNestedRequest() {
      return nestedRequestBuilder_ != null || nestedRequest_ != null;
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     * @return The nestedRequest.
     */
    public geo.v1.GeometryRequest getNestedRequest() {
      if (nestedRequestBuilder_ == null) {
        return nestedRequest_ == null ? geo.v1.GeometryRequest.getDefaultInstance() : nestedRequest_;
      } else {
        return nestedRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    public Builder setNestedRequest(geo.v1.GeometryRequest value) {
      if (nestedRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nestedRequest_ = value;
        onChanged();
      } else {
        nestedRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    public Builder setNestedRequest(
        geo.v1.GeometryRequest.Builder builderForValue) {
      if (nestedRequestBuilder_ == null) {
        nestedRequest_ = builderForValue.build();
        onChanged();
      } else {
        nestedRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    public Builder mergeNestedRequest(geo.v1.GeometryRequest value) {
      if (nestedRequestBuilder_ == null) {
        if (nestedRequest_ != null) {
          nestedRequest_ =
            geo.v1.GeometryRequest.newBuilder(nestedRequest_).mergeFrom(value).buildPartial();
        } else {
          nestedRequest_ = value;
        }
        onChanged();
      } else {
        nestedRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    public Builder clearNestedRequest() {
      if (nestedRequestBuilder_ == null) {
        nestedRequest_ = null;
        onChanged();
      } else {
        nestedRequest_ = null;
        nestedRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    public geo.v1.GeometryRequest.Builder getNestedRequestBuilder() {
      
      onChanged();
      return getNestedRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    public geo.v1.GeometryRequestOrBuilder getNestedRequestOrBuilder() {
      if (nestedRequestBuilder_ != null) {
        return nestedRequestBuilder_.getMessageOrBuilder();
      } else {
        return nestedRequest_ == null ?
            geo.v1.GeometryRequest.getDefaultInstance() : nestedRequest_;
      }
    }
    /**
     * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.GeometryRequest, geo.v1.GeometryRequest.Builder, geo.v1.GeometryRequestOrBuilder> 
        getNestedRequestFieldBuilder() {
      if (nestedRequestBuilder_ == null) {
        nestedRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            geo.v1.GeometryRequest, geo.v1.GeometryRequest.Builder, geo.v1.GeometryRequestOrBuilder>(
                getNestedRequest(),
                getParentForChildren(),
                isClean());
        nestedRequest_ = null;
      }
      return nestedRequestBuilder_;
    }

    private int resultEncodingType_ = 0;
    /**
     * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
     * @return The enum numeric value on the wire for resultEncodingType.
     */
    @java.lang.Override public int getResultEncodingTypeValue() {
      return resultEncodingType_;
    }
    /**
     * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
     * @param value The enum numeric value on the wire for resultEncodingType to set.
     * @return This builder for chaining.
     */
    public Builder setResultEncodingTypeValue(int value) {
      
      resultEncodingType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
     * @return The resultEncodingType.
     */
    @java.lang.Override
    public geo.v1.Encoding getResultEncodingType() {
      @SuppressWarnings("deprecation")
      geo.v1.Encoding result = geo.v1.Encoding.valueOf(resultEncodingType_);
      return result == null ? geo.v1.Encoding.UNRECOGNIZED : result;
    }
    /**
     * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
     * @param value The resultEncodingType to set.
     * @return This builder for chaining.
     */
    public Builder setResultEncodingType(geo.v1.Encoding value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      resultEncodingType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResultEncodingType() {
      
      resultEncodingType_ = 0;
      onChanged();
      return this;
    }

    private geo.v1.ProjectionData inputProj_;
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder> inputProjBuilder_;
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     * @return Whether the inputProj field is set.
     */
    public boolean hasInputProj() {
      return inputProjBuilder_ != null || inputProj_ != null;
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     * @return The inputProj.
     */
    public geo.v1.ProjectionData getInputProj() {
      if (inputProjBuilder_ == null) {
        return inputProj_ == null ? geo.v1.ProjectionData.getDefaultInstance() : inputProj_;
      } else {
        return inputProjBuilder_.getMessage();
      }
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    public Builder setInputProj(geo.v1.ProjectionData value) {
      if (inputProjBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inputProj_ = value;
        onChanged();
      } else {
        inputProjBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    public Builder setInputProj(
        geo.v1.ProjectionData.Builder builderForValue) {
      if (inputProjBuilder_ == null) {
        inputProj_ = builderForValue.build();
        onChanged();
      } else {
        inputProjBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    public Builder mergeInputProj(geo.v1.ProjectionData value) {
      if (inputProjBuilder_ == null) {
        if (inputProj_ != null) {
          inputProj_ =
            geo.v1.ProjectionData.newBuilder(inputProj_).mergeFrom(value).buildPartial();
        } else {
          inputProj_ = value;
        }
        onChanged();
      } else {
        inputProjBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    public Builder clearInputProj() {
      if (inputProjBuilder_ == null) {
        inputProj_ = null;
        onChanged();
      } else {
        inputProj_ = null;
        inputProjBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    public geo.v1.ProjectionData.Builder getInputProjBuilder() {
      
      onChanged();
      return getInputProjFieldBuilder().getBuilder();
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    public geo.v1.ProjectionDataOrBuilder getInputProjOrBuilder() {
      if (inputProjBuilder_ != null) {
        return inputProjBuilder_.getMessageOrBuilder();
      } else {
        return inputProj_ == null ?
            geo.v1.ProjectionData.getDefaultInstance() : inputProj_;
      }
    }
    /**
     * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder> 
        getInputProjFieldBuilder() {
      if (inputProjBuilder_ == null) {
        inputProjBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder>(
                getInputProj(),
                getParentForChildren(),
                isClean());
        inputProj_ = null;
      }
      return inputProjBuilder_;
    }

    private geo.v1.ProjectionData resultProj_;
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder> resultProjBuilder_;
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     * @return Whether the resultProj field is set.
     */
    public boolean hasResultProj() {
      return resultProjBuilder_ != null || resultProj_ != null;
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     * @return The resultProj.
     */
    public geo.v1.ProjectionData getResultProj() {
      if (resultProjBuilder_ == null) {
        return resultProj_ == null ? geo.v1.ProjectionData.getDefaultInstance() : resultProj_;
      } else {
        return resultProjBuilder_.getMessage();
      }
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    public Builder setResultProj(geo.v1.ProjectionData value) {
      if (resultProjBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resultProj_ = value;
        onChanged();
      } else {
        resultProjBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    public Builder setResultProj(
        geo.v1.ProjectionData.Builder builderForValue) {
      if (resultProjBuilder_ == null) {
        resultProj_ = builderForValue.build();
        onChanged();
      } else {
        resultProjBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    public Builder mergeResultProj(geo.v1.ProjectionData value) {
      if (resultProjBuilder_ == null) {
        if (resultProj_ != null) {
          resultProj_ =
            geo.v1.ProjectionData.newBuilder(resultProj_).mergeFrom(value).buildPartial();
        } else {
          resultProj_ = value;
        }
        onChanged();
      } else {
        resultProjBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    public Builder clearResultProj() {
      if (resultProjBuilder_ == null) {
        resultProj_ = null;
        onChanged();
      } else {
        resultProj_ = null;
        resultProjBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    public geo.v1.ProjectionData.Builder getResultProjBuilder() {
      
      onChanged();
      return getResultProjFieldBuilder().getBuilder();
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    public geo.v1.ProjectionDataOrBuilder getResultProjOrBuilder() {
      if (resultProjBuilder_ != null) {
        return resultProjBuilder_.getMessageOrBuilder();
      } else {
        return resultProj_ == null ?
            geo.v1.ProjectionData.getDefaultInstance() : resultProj_;
      }
    }
    /**
     * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder> 
        getResultProjFieldBuilder() {
      if (resultProjBuilder_ == null) {
        resultProjBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder>(
                getResultProj(),
                getParentForChildren(),
                isClean());
        resultProj_ = null;
      }
      return resultProjBuilder_;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 6 [json_name = "data"];</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 6 [json_name = "data"];</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 6 [json_name = "data"];</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <code>int64 size = 7 [json_name = "size"];</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }
    /**
     * <code>int64 size = 7 [json_name = "size"];</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(long value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 size = 7 [json_name = "size"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0L;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <code>int64 offset = 8 [json_name = "offset"];</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>int64 offset = 8 [json_name = "offset"];</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 8 [json_name = "offset"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      
      offset_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string file_name = 9 [json_name = "fileName"];</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_name = 9 [json_name = "fileName"];</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_name = 9 [json_name = "fileName"];</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 9 [json_name = "fileName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 9 [json_name = "fileName"];</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value;
      onChanged();
      return this;
    }

    private boolean isLastChunk_ ;
    /**
     * <code>bool is_last_chunk = 10 [json_name = "isLastChunk"];</code>
     * @return The isLastChunk.
     */
    @java.lang.Override
    public boolean getIsLastChunk() {
      return isLastChunk_;
    }
    /**
     * <code>bool is_last_chunk = 10 [json_name = "isLastChunk"];</code>
     * @param value The isLastChunk to set.
     * @return This builder for chaining.
     */
    public Builder setIsLastChunk(boolean value) {
      
      isLastChunk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_last_chunk = 10 [json_name = "isLastChunk"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLastChunk() {
      
      isLastChunk_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geo.v1.FileRequestChunk)
  }

  // @@protoc_insertion_point(class_scope:geo.v1.FileRequestChunk)
  private static final geo.v1.FileRequestChunk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new geo.v1.FileRequestChunk();
  }

  public static geo.v1.FileRequestChunk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileRequestChunk>
      PARSER = new com.google.protobuf.AbstractParser<FileRequestChunk>() {
    @java.lang.Override
    public FileRequestChunk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileRequestChunk(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileRequestChunk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileRequestChunk> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public geo.v1.FileRequestChunk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

