// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/geo/v1/geometry.proto

package geo.v1;

/**
 * Protobuf type {@code geo.v1.GeodeticInverse}
 */
public final class GeodeticInverse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geo.v1.GeodeticInverse)
    GeodeticInverseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeodeticInverse.newBuilder() to construct.
  private GeodeticInverse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeodeticInverse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeodeticInverse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GeodeticInverse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            az12_ = input.readDouble();
            break;
          }
          case 17: {

            az21_ = input.readDouble();
            break;
          }
          case 25: {

            distance_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return geo.v1.GeometryProto.internal_static_geo_v1_GeodeticInverse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return geo.v1.GeometryProto.internal_static_geo_v1_GeodeticInverse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            geo.v1.GeodeticInverse.class, geo.v1.GeodeticInverse.Builder.class);
  }

  public static final int AZ12_FIELD_NUMBER = 1;
  private double az12_;
  /**
   * <pre>
   * Azimuth from the first to the second point
   * </pre>
   *
   * <code>double az12 = 1 [json_name = "az12"];</code>
   * @return The az12.
   */
  @java.lang.Override
  public double getAz12() {
    return az12_;
  }

  public static final int AZ21_FIELD_NUMBER = 2;
  private double az21_;
  /**
   * <pre>
   * Azimuth from the second to the first point
   * </pre>
   *
   * <code>double az21 = 2 [json_name = "az21"];</code>
   * @return The az21.
   */
  @java.lang.Override
  public double getAz21() {
    return az21_;
  }

  public static final int DISTANCE_FIELD_NUMBER = 3;
  private double distance_;
  /**
   * <pre>
   * Geodesic distance
   * </pre>
   *
   * <code>double distance = 3 [json_name = "distance"];</code>
   * @return The distance.
   */
  @java.lang.Override
  public double getDistance() {
    return distance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(az12_) != 0) {
      output.writeDouble(1, az12_);
    }
    if (java.lang.Double.doubleToRawLongBits(az21_) != 0) {
      output.writeDouble(2, az21_);
    }
    if (java.lang.Double.doubleToRawLongBits(distance_) != 0) {
      output.writeDouble(3, distance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(az12_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, az12_);
    }
    if (java.lang.Double.doubleToRawLongBits(az21_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, az21_);
    }
    if (java.lang.Double.doubleToRawLongBits(distance_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, distance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof geo.v1.GeodeticInverse)) {
      return super.equals(obj);
    }
    geo.v1.GeodeticInverse other = (geo.v1.GeodeticInverse) obj;

    if (java.lang.Double.doubleToLongBits(getAz12())
        != java.lang.Double.doubleToLongBits(
            other.getAz12())) return false;
    if (java.lang.Double.doubleToLongBits(getAz21())
        != java.lang.Double.doubleToLongBits(
            other.getAz21())) return false;
    if (java.lang.Double.doubleToLongBits(getDistance())
        != java.lang.Double.doubleToLongBits(
            other.getDistance())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AZ12_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAz12()));
    hash = (37 * hash) + AZ21_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAz21()));
    hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDistance()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static geo.v1.GeodeticInverse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.GeodeticInverse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.GeodeticInverse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static geo.v1.GeodeticInverse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static geo.v1.GeodeticInverse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static geo.v1.GeodeticInverse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(geo.v1.GeodeticInverse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code geo.v1.GeodeticInverse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geo.v1.GeodeticInverse)
      geo.v1.GeodeticInverseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return geo.v1.GeometryProto.internal_static_geo_v1_GeodeticInverse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return geo.v1.GeometryProto.internal_static_geo_v1_GeodeticInverse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              geo.v1.GeodeticInverse.class, geo.v1.GeodeticInverse.Builder.class);
    }

    // Construct using geo.v1.GeodeticInverse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      az12_ = 0D;

      az21_ = 0D;

      distance_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return geo.v1.GeometryProto.internal_static_geo_v1_GeodeticInverse_descriptor;
    }

    @java.lang.Override
    public geo.v1.GeodeticInverse getDefaultInstanceForType() {
      return geo.v1.GeodeticInverse.getDefaultInstance();
    }

    @java.lang.Override
    public geo.v1.GeodeticInverse build() {
      geo.v1.GeodeticInverse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public geo.v1.GeodeticInverse buildPartial() {
      geo.v1.GeodeticInverse result = new geo.v1.GeodeticInverse(this);
      result.az12_ = az12_;
      result.az21_ = az21_;
      result.distance_ = distance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof geo.v1.GeodeticInverse) {
        return mergeFrom((geo.v1.GeodeticInverse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(geo.v1.GeodeticInverse other) {
      if (other == geo.v1.GeodeticInverse.getDefaultInstance()) return this;
      if (other.getAz12() != 0D) {
        setAz12(other.getAz12());
      }
      if (other.getAz21() != 0D) {
        setAz21(other.getAz21());
      }
      if (other.getDistance() != 0D) {
        setDistance(other.getDistance());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      geo.v1.GeodeticInverse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (geo.v1.GeodeticInverse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double az12_ ;
    /**
     * <pre>
     * Azimuth from the first to the second point
     * </pre>
     *
     * <code>double az12 = 1 [json_name = "az12"];</code>
     * @return The az12.
     */
    @java.lang.Override
    public double getAz12() {
      return az12_;
    }
    /**
     * <pre>
     * Azimuth from the first to the second point
     * </pre>
     *
     * <code>double az12 = 1 [json_name = "az12"];</code>
     * @param value The az12 to set.
     * @return This builder for chaining.
     */
    public Builder setAz12(double value) {
      
      az12_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Azimuth from the first to the second point
     * </pre>
     *
     * <code>double az12 = 1 [json_name = "az12"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAz12() {
      
      az12_ = 0D;
      onChanged();
      return this;
    }

    private double az21_ ;
    /**
     * <pre>
     * Azimuth from the second to the first point
     * </pre>
     *
     * <code>double az21 = 2 [json_name = "az21"];</code>
     * @return The az21.
     */
    @java.lang.Override
    public double getAz21() {
      return az21_;
    }
    /**
     * <pre>
     * Azimuth from the second to the first point
     * </pre>
     *
     * <code>double az21 = 2 [json_name = "az21"];</code>
     * @param value The az21 to set.
     * @return This builder for chaining.
     */
    public Builder setAz21(double value) {
      
      az21_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Azimuth from the second to the first point
     * </pre>
     *
     * <code>double az21 = 2 [json_name = "az21"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAz21() {
      
      az21_ = 0D;
      onChanged();
      return this;
    }

    private double distance_ ;
    /**
     * <pre>
     * Geodesic distance
     * </pre>
     *
     * <code>double distance = 3 [json_name = "distance"];</code>
     * @return The distance.
     */
    @java.lang.Override
    public double getDistance() {
      return distance_;
    }
    /**
     * <pre>
     * Geodesic distance
     * </pre>
     *
     * <code>double distance = 3 [json_name = "distance"];</code>
     * @param value The distance to set.
     * @return This builder for chaining.
     */
    public Builder setDistance(double value) {
      
      distance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Geodesic distance
     * </pre>
     *
     * <code>double distance = 3 [json_name = "distance"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDistance() {
      
      distance_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geo.v1.GeodeticInverse)
  }

  // @@protoc_insertion_point(class_scope:geo.v1.GeodeticInverse)
  private static final geo.v1.GeodeticInverse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new geo.v1.GeodeticInverse();
  }

  public static geo.v1.GeodeticInverse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeodeticInverse>
      PARSER = new com.google.protobuf.AbstractParser<GeodeticInverse>() {
    @java.lang.Override
    public GeodeticInverse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GeodeticInverse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GeodeticInverse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeodeticInverse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public geo.v1.GeodeticInverse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

