// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/geo/v1/geometry.proto

package geo.v1;

public interface ProjectionDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geo.v1.ProjectionData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * epsg wkid (well know id), or srid (spatial reference id) of the projected or geographic coordinate system
   * </pre>
   *
   * <code>int32 epsg = 1 [json_name = "epsg"];</code>
   * @return Whether the epsg field is set.
   */
  boolean hasEpsg();
  /**
   * <pre>
   * epsg wkid (well know id), or srid (spatial reference id) of the projected or geographic coordinate system
   * </pre>
   *
   * <code>int32 epsg = 1 [json_name = "epsg"];</code>
   * @return The epsg.
   */
  int getEpsg();

  /**
   * <pre>
   * proj string describing a projection or geographic coordinate system https://proj4.org/usage/projections.html
   * </pre>
   *
   * <code>string proj4 = 2 [json_name = "proj4"];</code>
   * @return Whether the proj4 field is set.
   */
  boolean hasProj4();
  /**
   * <pre>
   * proj string describing a projection or geographic coordinate system https://proj4.org/usage/projections.html
   * </pre>
   *
   * <code>string proj4 = 2 [json_name = "proj4"];</code>
   * @return The proj4.
   */
  java.lang.String getProj4();
  /**
   * <pre>
   * proj string describing a projection or geographic coordinate system https://proj4.org/usage/projections.html
   * </pre>
   *
   * <code>string proj4 = 2 [json_name = "proj4"];</code>
   * @return The bytes for proj4.
   */
  com.google.protobuf.ByteString
      getProj4Bytes();

  /**
   * <pre>
   * custom projection
   * </pre>
   *
   * <code>.geo.v1.ProjectionData.Custom custom = 3 [json_name = "custom"];</code>
   * @return Whether the custom field is set.
   */
  boolean hasCustom();
  /**
   * <pre>
   * custom projection
   * </pre>
   *
   * <code>.geo.v1.ProjectionData.Custom custom = 3 [json_name = "custom"];</code>
   * @return The custom.
   */
  geo.v1.ProjectionData.Custom getCustom();
  /**
   * <pre>
   * custom projection
   * </pre>
   *
   * <code>.geo.v1.ProjectionData.Custom custom = 3 [json_name = "custom"];</code>
   */
  geo.v1.ProjectionData.CustomOrBuilder getCustomOrBuilder();

  /**
   * <pre>
   * well-known text string of spatial reference
   * </pre>
   *
   * <code>string wkt = 4 [json_name = "wkt"];</code>
   * @return Whether the wkt field is set.
   */
  boolean hasWkt();
  /**
   * <pre>
   * well-known text string of spatial reference
   * </pre>
   *
   * <code>string wkt = 4 [json_name = "wkt"];</code>
   * @return The wkt.
   */
  java.lang.String getWkt();
  /**
   * <pre>
   * well-known text string of spatial reference
   * </pre>
   *
   * <code>string wkt = 4 [json_name = "wkt"];</code>
   * @return The bytes for wkt.
   */
  com.google.protobuf.ByteString
      getWktBytes();

  /**
   * <code>.geo.v1.GeometryData geometry = 10 [json_name = "geometry"];</code>
   * @return Whether the geometry field is set.
   */
  boolean hasGeometry();
  /**
   * <code>.geo.v1.GeometryData geometry = 10 [json_name = "geometry"];</code>
   * @return The geometry.
   */
  geo.v1.GeometryData getGeometry();
  /**
   * <code>.geo.v1.GeometryData geometry = 10 [json_name = "geometry"];</code>
   */
  geo.v1.GeometryDataOrBuilder getGeometryOrBuilder();

  /**
   * <code>.geo.v1.EnvelopeData bbox = 11 [json_name = "bbox"];</code>
   * @return Whether the bbox field is set.
   */
  boolean hasBbox();
  /**
   * <code>.geo.v1.EnvelopeData bbox = 11 [json_name = "bbox"];</code>
   * @return The bbox.
   */
  geo.v1.EnvelopeData getBbox();
  /**
   * <code>.geo.v1.EnvelopeData bbox = 11 [json_name = "bbox"];</code>
   */
  geo.v1.EnvelopeDataOrBuilder getBboxOrBuilder();

  /**
   * <code>.geo.v1.GeometryData centroid = 12 [json_name = "centroid"];</code>
   * @return Whether the centroid field is set.
   */
  boolean hasCentroid();
  /**
   * <code>.geo.v1.GeometryData centroid = 12 [json_name = "centroid"];</code>
   * @return The centroid.
   */
  geo.v1.GeometryData getCentroid();
  /**
   * <code>.geo.v1.GeometryData centroid = 12 [json_name = "centroid"];</code>
   */
  geo.v1.GeometryDataOrBuilder getCentroidOrBuilder();

  /**
   * <code>repeated uint32 shape = 8 [json_name = "shape"];</code>
   * @return A list containing the shape.
   */
  java.util.List<java.lang.Integer> getShapeList();
  /**
   * <code>repeated uint32 shape = 8 [json_name = "shape"];</code>
   * @return The count of shape.
   */
  int getShapeCount();
  /**
   * <code>repeated uint32 shape = 8 [json_name = "shape"];</code>
   * @param index The index of the element to return.
   * @return The shape at the given index.
   */
  int getShape(int index);

  /**
   * <code>repeated double transform = 9 [json_name = "transform"];</code>
   * @return A list containing the transform.
   */
  java.util.List<java.lang.Double> getTransformList();
  /**
   * <code>repeated double transform = 9 [json_name = "transform"];</code>
   * @return The count of transform.
   */
  int getTransformCount();
  /**
   * <code>repeated double transform = 9 [json_name = "transform"];</code>
   * @param index The index of the element to return.
   * @return The transform at the given index.
   */
  double getTransform(int index);

  public geo.v1.ProjectionData.DefinitionCase getDefinitionCase();
}
