// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/route_guide/v1/route_guide.proto

package io.grpc.route_guide.v1;

public interface RouteChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route_guide.v1.RouteChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.route_guide.v1.RouteNote route_note = 1 [json_name = "routeNote"];</code>
   * @return Whether the routeNote field is set.
   */
  boolean hasRouteNote();
  /**
   * <code>.route_guide.v1.RouteNote route_note = 1 [json_name = "routeNote"];</code>
   * @return The routeNote.
   */
  io.grpc.route_guide.v1.RouteNote getRouteNote();
  /**
   * <code>.route_guide.v1.RouteNote route_note = 1 [json_name = "routeNote"];</code>
   */
  io.grpc.route_guide.v1.RouteNoteOrBuilder getRouteNoteOrBuilder();
}
