// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/geo/v1/geometry.proto

package geo.v1;

/**
 * <pre>
 * Container for Envelope data (bounding box), x and y min and max and an optional spatial reference
 * </pre>
 *
 * Protobuf type {@code geo.v1.EnvelopeData}
 */
public final class EnvelopeData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geo.v1.EnvelopeData)
    EnvelopeDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnvelopeData.newBuilder() to construct.
  private EnvelopeData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnvelopeData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnvelopeData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnvelopeData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            xmin_ = input.readDouble();
            break;
          }
          case 17: {

            ymin_ = input.readDouble();
            break;
          }
          case 25: {

            xmax_ = input.readDouble();
            break;
          }
          case 33: {

            ymax_ = input.readDouble();
            break;
          }
          case 42: {
            geo.v1.ProjectionData.Builder subBuilder = null;
            if (proj_ != null) {
              subBuilder = proj_.toBuilder();
            }
            proj_ = input.readMessage(geo.v1.ProjectionData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(proj_);
              proj_ = subBuilder.buildPartial();
            }

            break;
          }
          case 49: {

            zmin_ = input.readDouble();
            break;
          }
          case 57: {

            zmax_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return geo.v1.GeometryProto.internal_static_geo_v1_EnvelopeData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return geo.v1.GeometryProto.internal_static_geo_v1_EnvelopeData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            geo.v1.EnvelopeData.class, geo.v1.EnvelopeData.Builder.class);
  }

  public static final int XMIN_FIELD_NUMBER = 1;
  private double xmin_;
  /**
   * <pre>
   * min x value
   * </pre>
   *
   * <code>double xmin = 1 [json_name = "xmin"];</code>
   * @return The xmin.
   */
  @java.lang.Override
  public double getXmin() {
    return xmin_;
  }

  public static final int YMIN_FIELD_NUMBER = 2;
  private double ymin_;
  /**
   * <pre>
   * min y value
   * </pre>
   *
   * <code>double ymin = 2 [json_name = "ymin"];</code>
   * @return The ymin.
   */
  @java.lang.Override
  public double getYmin() {
    return ymin_;
  }

  public static final int XMAX_FIELD_NUMBER = 3;
  private double xmax_;
  /**
   * <pre>
   * max x value
   * </pre>
   *
   * <code>double xmax = 3 [json_name = "xmax"];</code>
   * @return The xmax.
   */
  @java.lang.Override
  public double getXmax() {
    return xmax_;
  }

  public static final int YMAX_FIELD_NUMBER = 4;
  private double ymax_;
  /**
   * <pre>
   * max y value
   * </pre>
   *
   * <code>double ymax = 4 [json_name = "ymax"];</code>
   * @return The ymax.
   */
  @java.lang.Override
  public double getYmax() {
    return ymax_;
  }

  public static final int PROJ_FIELD_NUMBER = 5;
  private geo.v1.ProjectionData proj_;
  /**
   * <pre>
   * spatial reference of envelope
   * </pre>
   *
   * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
   * @return Whether the proj field is set.
   */
  @java.lang.Override
  public boolean hasProj() {
    return proj_ != null;
  }
  /**
   * <pre>
   * spatial reference of envelope
   * </pre>
   *
   * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
   * @return The proj.
   */
  @java.lang.Override
  public geo.v1.ProjectionData getProj() {
    return proj_ == null ? geo.v1.ProjectionData.getDefaultInstance() : proj_;
  }
  /**
   * <pre>
   * spatial reference of envelope
   * </pre>
   *
   * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
   */
  @java.lang.Override
  public geo.v1.ProjectionDataOrBuilder getProjOrBuilder() {
    return getProj();
  }

  public static final int ZMIN_FIELD_NUMBER = 6;
  private double zmin_;
  /**
   * <code>double zmin = 6 [json_name = "zmin"];</code>
   * @return The zmin.
   */
  @java.lang.Override
  public double getZmin() {
    return zmin_;
  }

  public static final int ZMAX_FIELD_NUMBER = 7;
  private double zmax_;
  /**
   * <code>double zmax = 7 [json_name = "zmax"];</code>
   * @return The zmax.
   */
  @java.lang.Override
  public double getZmax() {
    return zmax_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(xmin_) != 0) {
      output.writeDouble(1, xmin_);
    }
    if (java.lang.Double.doubleToRawLongBits(ymin_) != 0) {
      output.writeDouble(2, ymin_);
    }
    if (java.lang.Double.doubleToRawLongBits(xmax_) != 0) {
      output.writeDouble(3, xmax_);
    }
    if (java.lang.Double.doubleToRawLongBits(ymax_) != 0) {
      output.writeDouble(4, ymax_);
    }
    if (proj_ != null) {
      output.writeMessage(5, getProj());
    }
    if (java.lang.Double.doubleToRawLongBits(zmin_) != 0) {
      output.writeDouble(6, zmin_);
    }
    if (java.lang.Double.doubleToRawLongBits(zmax_) != 0) {
      output.writeDouble(7, zmax_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(xmin_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, xmin_);
    }
    if (java.lang.Double.doubleToRawLongBits(ymin_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, ymin_);
    }
    if (java.lang.Double.doubleToRawLongBits(xmax_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, xmax_);
    }
    if (java.lang.Double.doubleToRawLongBits(ymax_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, ymax_);
    }
    if (proj_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getProj());
    }
    if (java.lang.Double.doubleToRawLongBits(zmin_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, zmin_);
    }
    if (java.lang.Double.doubleToRawLongBits(zmax_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, zmax_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof geo.v1.EnvelopeData)) {
      return super.equals(obj);
    }
    geo.v1.EnvelopeData other = (geo.v1.EnvelopeData) obj;

    if (java.lang.Double.doubleToLongBits(getXmin())
        != java.lang.Double.doubleToLongBits(
            other.getXmin())) return false;
    if (java.lang.Double.doubleToLongBits(getYmin())
        != java.lang.Double.doubleToLongBits(
            other.getYmin())) return false;
    if (java.lang.Double.doubleToLongBits(getXmax())
        != java.lang.Double.doubleToLongBits(
            other.getXmax())) return false;
    if (java.lang.Double.doubleToLongBits(getYmax())
        != java.lang.Double.doubleToLongBits(
            other.getYmax())) return false;
    if (hasProj() != other.hasProj()) return false;
    if (hasProj()) {
      if (!getProj()
          .equals(other.getProj())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getZmin())
        != java.lang.Double.doubleToLongBits(
            other.getZmin())) return false;
    if (java.lang.Double.doubleToLongBits(getZmax())
        != java.lang.Double.doubleToLongBits(
            other.getZmax())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + XMIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getXmin()));
    hash = (37 * hash) + YMIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getYmin()));
    hash = (37 * hash) + XMAX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getXmax()));
    hash = (37 * hash) + YMAX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getYmax()));
    if (hasProj()) {
      hash = (37 * hash) + PROJ_FIELD_NUMBER;
      hash = (53 * hash) + getProj().hashCode();
    }
    hash = (37 * hash) + ZMIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZmin()));
    hash = (37 * hash) + ZMAX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZmax()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static geo.v1.EnvelopeData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.EnvelopeData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.EnvelopeData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.EnvelopeData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.EnvelopeData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static geo.v1.EnvelopeData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static geo.v1.EnvelopeData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static geo.v1.EnvelopeData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static geo.v1.EnvelopeData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static geo.v1.EnvelopeData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static geo.v1.EnvelopeData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static geo.v1.EnvelopeData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(geo.v1.EnvelopeData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Container for Envelope data (bounding box), x and y min and max and an optional spatial reference
   * </pre>
   *
   * Protobuf type {@code geo.v1.EnvelopeData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geo.v1.EnvelopeData)
      geo.v1.EnvelopeDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return geo.v1.GeometryProto.internal_static_geo_v1_EnvelopeData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return geo.v1.GeometryProto.internal_static_geo_v1_EnvelopeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              geo.v1.EnvelopeData.class, geo.v1.EnvelopeData.Builder.class);
    }

    // Construct using geo.v1.EnvelopeData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      xmin_ = 0D;

      ymin_ = 0D;

      xmax_ = 0D;

      ymax_ = 0D;

      if (projBuilder_ == null) {
        proj_ = null;
      } else {
        proj_ = null;
        projBuilder_ = null;
      }
      zmin_ = 0D;

      zmax_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return geo.v1.GeometryProto.internal_static_geo_v1_EnvelopeData_descriptor;
    }

    @java.lang.Override
    public geo.v1.EnvelopeData getDefaultInstanceForType() {
      return geo.v1.EnvelopeData.getDefaultInstance();
    }

    @java.lang.Override
    public geo.v1.EnvelopeData build() {
      geo.v1.EnvelopeData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public geo.v1.EnvelopeData buildPartial() {
      geo.v1.EnvelopeData result = new geo.v1.EnvelopeData(this);
      result.xmin_ = xmin_;
      result.ymin_ = ymin_;
      result.xmax_ = xmax_;
      result.ymax_ = ymax_;
      if (projBuilder_ == null) {
        result.proj_ = proj_;
      } else {
        result.proj_ = projBuilder_.build();
      }
      result.zmin_ = zmin_;
      result.zmax_ = zmax_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof geo.v1.EnvelopeData) {
        return mergeFrom((geo.v1.EnvelopeData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(geo.v1.EnvelopeData other) {
      if (other == geo.v1.EnvelopeData.getDefaultInstance()) return this;
      if (other.getXmin() != 0D) {
        setXmin(other.getXmin());
      }
      if (other.getYmin() != 0D) {
        setYmin(other.getYmin());
      }
      if (other.getXmax() != 0D) {
        setXmax(other.getXmax());
      }
      if (other.getYmax() != 0D) {
        setYmax(other.getYmax());
      }
      if (other.hasProj()) {
        mergeProj(other.getProj());
      }
      if (other.getZmin() != 0D) {
        setZmin(other.getZmin());
      }
      if (other.getZmax() != 0D) {
        setZmax(other.getZmax());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      geo.v1.EnvelopeData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (geo.v1.EnvelopeData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double xmin_ ;
    /**
     * <pre>
     * min x value
     * </pre>
     *
     * <code>double xmin = 1 [json_name = "xmin"];</code>
     * @return The xmin.
     */
    @java.lang.Override
    public double getXmin() {
      return xmin_;
    }
    /**
     * <pre>
     * min x value
     * </pre>
     *
     * <code>double xmin = 1 [json_name = "xmin"];</code>
     * @param value The xmin to set.
     * @return This builder for chaining.
     */
    public Builder setXmin(double value) {
      
      xmin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * min x value
     * </pre>
     *
     * <code>double xmin = 1 [json_name = "xmin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearXmin() {
      
      xmin_ = 0D;
      onChanged();
      return this;
    }

    private double ymin_ ;
    /**
     * <pre>
     * min y value
     * </pre>
     *
     * <code>double ymin = 2 [json_name = "ymin"];</code>
     * @return The ymin.
     */
    @java.lang.Override
    public double getYmin() {
      return ymin_;
    }
    /**
     * <pre>
     * min y value
     * </pre>
     *
     * <code>double ymin = 2 [json_name = "ymin"];</code>
     * @param value The ymin to set.
     * @return This builder for chaining.
     */
    public Builder setYmin(double value) {
      
      ymin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * min y value
     * </pre>
     *
     * <code>double ymin = 2 [json_name = "ymin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearYmin() {
      
      ymin_ = 0D;
      onChanged();
      return this;
    }

    private double xmax_ ;
    /**
     * <pre>
     * max x value
     * </pre>
     *
     * <code>double xmax = 3 [json_name = "xmax"];</code>
     * @return The xmax.
     */
    @java.lang.Override
    public double getXmax() {
      return xmax_;
    }
    /**
     * <pre>
     * max x value
     * </pre>
     *
     * <code>double xmax = 3 [json_name = "xmax"];</code>
     * @param value The xmax to set.
     * @return This builder for chaining.
     */
    public Builder setXmax(double value) {
      
      xmax_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * max x value
     * </pre>
     *
     * <code>double xmax = 3 [json_name = "xmax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearXmax() {
      
      xmax_ = 0D;
      onChanged();
      return this;
    }

    private double ymax_ ;
    /**
     * <pre>
     * max y value
     * </pre>
     *
     * <code>double ymax = 4 [json_name = "ymax"];</code>
     * @return The ymax.
     */
    @java.lang.Override
    public double getYmax() {
      return ymax_;
    }
    /**
     * <pre>
     * max y value
     * </pre>
     *
     * <code>double ymax = 4 [json_name = "ymax"];</code>
     * @param value The ymax to set.
     * @return This builder for chaining.
     */
    public Builder setYmax(double value) {
      
      ymax_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * max y value
     * </pre>
     *
     * <code>double ymax = 4 [json_name = "ymax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearYmax() {
      
      ymax_ = 0D;
      onChanged();
      return this;
    }

    private geo.v1.ProjectionData proj_;
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder> projBuilder_;
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     * @return Whether the proj field is set.
     */
    public boolean hasProj() {
      return projBuilder_ != null || proj_ != null;
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     * @return The proj.
     */
    public geo.v1.ProjectionData getProj() {
      if (projBuilder_ == null) {
        return proj_ == null ? geo.v1.ProjectionData.getDefaultInstance() : proj_;
      } else {
        return projBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    public Builder setProj(geo.v1.ProjectionData value) {
      if (projBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        proj_ = value;
        onChanged();
      } else {
        projBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    public Builder setProj(
        geo.v1.ProjectionData.Builder builderForValue) {
      if (projBuilder_ == null) {
        proj_ = builderForValue.build();
        onChanged();
      } else {
        projBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    public Builder mergeProj(geo.v1.ProjectionData value) {
      if (projBuilder_ == null) {
        if (proj_ != null) {
          proj_ =
            geo.v1.ProjectionData.newBuilder(proj_).mergeFrom(value).buildPartial();
        } else {
          proj_ = value;
        }
        onChanged();
      } else {
        projBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    public Builder clearProj() {
      if (projBuilder_ == null) {
        proj_ = null;
        onChanged();
      } else {
        proj_ = null;
        projBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    public geo.v1.ProjectionData.Builder getProjBuilder() {
      
      onChanged();
      return getProjFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    public geo.v1.ProjectionDataOrBuilder getProjOrBuilder() {
      if (projBuilder_ != null) {
        return projBuilder_.getMessageOrBuilder();
      } else {
        return proj_ == null ?
            geo.v1.ProjectionData.getDefaultInstance() : proj_;
      }
    }
    /**
     * <pre>
     * spatial reference of envelope
     * </pre>
     *
     * <code>.geo.v1.ProjectionData proj = 5 [json_name = "proj"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder> 
        getProjFieldBuilder() {
      if (projBuilder_ == null) {
        projBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            geo.v1.ProjectionData, geo.v1.ProjectionData.Builder, geo.v1.ProjectionDataOrBuilder>(
                getProj(),
                getParentForChildren(),
                isClean());
        proj_ = null;
      }
      return projBuilder_;
    }

    private double zmin_ ;
    /**
     * <code>double zmin = 6 [json_name = "zmin"];</code>
     * @return The zmin.
     */
    @java.lang.Override
    public double getZmin() {
      return zmin_;
    }
    /**
     * <code>double zmin = 6 [json_name = "zmin"];</code>
     * @param value The zmin to set.
     * @return This builder for chaining.
     */
    public Builder setZmin(double value) {
      
      zmin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double zmin = 6 [json_name = "zmin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearZmin() {
      
      zmin_ = 0D;
      onChanged();
      return this;
    }

    private double zmax_ ;
    /**
     * <code>double zmax = 7 [json_name = "zmax"];</code>
     * @return The zmax.
     */
    @java.lang.Override
    public double getZmax() {
      return zmax_;
    }
    /**
     * <code>double zmax = 7 [json_name = "zmax"];</code>
     * @param value The zmax to set.
     * @return This builder for chaining.
     */
    public Builder setZmax(double value) {
      
      zmax_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double zmax = 7 [json_name = "zmax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearZmax() {
      
      zmax_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geo.v1.EnvelopeData)
  }

  // @@protoc_insertion_point(class_scope:geo.v1.EnvelopeData)
  private static final geo.v1.EnvelopeData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new geo.v1.EnvelopeData();
  }

  public static geo.v1.EnvelopeData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnvelopeData>
      PARSER = new com.google.protobuf.AbstractParser<EnvelopeData>() {
    @java.lang.Override
    public EnvelopeData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnvelopeData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnvelopeData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnvelopeData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public geo.v1.EnvelopeData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

