// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/geo/v1/geometry.proto

package geo.v1;

public interface FileRequestChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geo.v1.FileRequestChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
   * @return Whether the nestedRequest field is set.
   */
  boolean hasNestedRequest();
  /**
   * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
   * @return The nestedRequest.
   */
  geo.v1.GeometryRequest getNestedRequest();
  /**
   * <code>.geo.v1.GeometryRequest nested_request = 1 [json_name = "nestedRequest"];</code>
   */
  geo.v1.GeometryRequestOrBuilder getNestedRequestOrBuilder();

  /**
   * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
   * @return The enum numeric value on the wire for resultEncodingType.
   */
  int getResultEncodingTypeValue();
  /**
   * <code>.geo.v1.Encoding result_encoding_type = 2 [json_name = "resultEncodingType"];</code>
   * @return The resultEncodingType.
   */
  geo.v1.Encoding getResultEncodingType();

  /**
   * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
   * @return Whether the inputProj field is set.
   */
  boolean hasInputProj();
  /**
   * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
   * @return The inputProj.
   */
  geo.v1.ProjectionData getInputProj();
  /**
   * <code>.geo.v1.ProjectionData input_proj = 3 [json_name = "inputProj"];</code>
   */
  geo.v1.ProjectionDataOrBuilder getInputProjOrBuilder();

  /**
   * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
   * @return Whether the resultProj field is set.
   */
  boolean hasResultProj();
  /**
   * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
   * @return The resultProj.
   */
  geo.v1.ProjectionData getResultProj();
  /**
   * <code>.geo.v1.ProjectionData result_proj = 5 [json_name = "resultProj"];</code>
   */
  geo.v1.ProjectionDataOrBuilder getResultProjOrBuilder();

  /**
   * <code>bytes data = 6 [json_name = "data"];</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int64 size = 7 [json_name = "size"];</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>int64 offset = 8 [json_name = "offset"];</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>string file_name = 9 [json_name = "fileName"];</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 9 [json_name = "fileName"];</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>bool is_last_chunk = 10 [json_name = "isLastChunk"];</code>
   * @return The isLastChunk.
   */
  boolean getIsLastChunk();
}
