// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide/v1/route_guide.proto

package io.grpc.route_guide.v1;

public interface ListFeaturesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route_guide.v1.ListFeaturesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.route_guide.v1.Point lo = 1 [json_name = "lo"];</code>
   * @return Whether the lo field is set.
   */
  boolean hasLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.route_guide.v1.Point lo = 1 [json_name = "lo"];</code>
   * @return The lo.
   */
  io.grpc.route_guide.v1.Point getLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.route_guide.v1.Point lo = 1 [json_name = "lo"];</code>
   */
  io.grpc.route_guide.v1.PointOrBuilder getLoOrBuilder();

  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.route_guide.v1.Point hi = 2 [json_name = "hi"];</code>
   * @return Whether the hi field is set.
   */
  boolean hasHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.route_guide.v1.Point hi = 2 [json_name = "hi"];</code>
   * @return The hi.
   */
  io.grpc.route_guide.v1.Point getHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.route_guide.v1.Point hi = 2 [json_name = "hi"];</code>
   */
  io.grpc.route_guide.v1.PointOrBuilder getHiOrBuilder();
}
