// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/route_guide/v1/route_guide.proto

package io.grpc.route_guide.v1;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route_guide.v1.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1 [json_name = "latitude"];</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2 [json_name = "longitude"];</code>
   * @return The longitude.
   */
  int getLongitude();
}
