// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide/v1/stuff.proto

package io.grpc.route_guide.v1;

public interface RoutePointTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route_guide.v1.RoutePointTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.route_guide.v1.Point point = 1 [json_name = "point"];</code>
   * @return Whether the point field is set.
   */
  boolean hasPoint();
  /**
   * <code>.route_guide.v1.Point point = 1 [json_name = "point"];</code>
   * @return The point.
   */
  io.grpc.route_guide.v1.Point getPoint();
  /**
   * <code>.route_guide.v1.Point point = 1 [json_name = "point"];</code>
   */
  io.grpc.route_guide.v1.PointOrBuilder getPointOrBuilder();
}
