// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide/v1/stuff.proto

package io.grpc.route_guide.v1;

public final class StuffProto {
  private StuffProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_route_guide_v1_RoutePointTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_route_guide_v1_RoutePointTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032route_guide/v1/stuff.proto\022\016route_guid" +
      "e.v1\032 route_guide/v1/route_guide.proto\"=" +
      "\n\016RoutePointTest\022+\n\005point\030\001 \001(\0132\025.route_" +
      "guide.v1.PointR\005pointBy\n\026io.grpc.route_g" +
      "uide.v1B\nStuffProtoP\001Z2github.com/davidr" +
      "aleigh/mono/golang/route_guide/v1\242\002\003RTG\252" +
      "\002\026io.grpc.route_guide.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.grpc.route_guide.v1.RouteGuideProto.getDescriptor(),
        });
    internal_static_route_guide_v1_RoutePointTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_route_guide_v1_RoutePointTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_route_guide_v1_RoutePointTest_descriptor,
        new java.lang.String[] { "Point", });
    io.grpc.route_guide.v1.RouteGuideProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
